### ISSUE TITLE
MUDA.py should be lowercase. 

### ISSUE THREAD

**Issue by marcovnyc** [zyenapz/Star-Fighter#2]
Great project.  I was able to clone your repo and run the app but it crashed 
I ran with python3 game.py and got the error

ModuleNoFoundError: no module named 'data.scripts.muda'

I noticed the scripts directory had the muda file but in uppercase

MUDA.py

I renamed the file to lower case and ran python3 again and it worked.  

Cheers

**Comment by fmtayag** [comment]
Huh, in my desktop it is named in lowercase. GitHub must not have pushed it to the repository when I renamed it. Weird. Anyways, thank you very much for reporting the issue!
